version: '3'

services:
  bot:
    build: .
    restart: always
    env_file: ${ENV_FILE}
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:alpine
    env_file: ${ENV_FILE}
  postgres:
    image: postgres:alpine
    env_file: ${ENV_FILE}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: